// Squamish Dyno: game engine. Pure logic, no DOM, so it can be simulated.
//
// You hang from a hold by one arm and swing like a pendulum. Holding the
// button pumps the swing; letting go launches you. If your hand passes a hold
// mid-air you catch it. Each hold only lasts a few seconds.
//
// The route is generated by simulating real jumps: every new hold sits on the
// flight path of a full-power swing from the previous one, so every route is
// climbable.

export type HoldType = "start" | "bolt" | "jug" | "crimp" | "sloper" | "summit";
export type Plan = { dir: 1 | -1; theta: number };
export type Hold = {
  id: number;
  x: number;
  y: number;
  type: HoldType;
  grip: number;
  plan?: Plan;
};
export type Phase = "hanging" | "flying" | "falling" | "summit";
export type Vec = { x: number; y: number };

// World units are pixels with y pointing up; y = 0 is the forest floor.
export const W = 480;
export const H = 640;
export const DT = 1 / 120;
export const PX_PER_M = 10;
export const SUMMIT_M = 702;
export const START_Y = 215;
export const SUMMIT_Y = START_Y + SUMMIT_M * PX_PER_M;
export const ARM = 64; // hold to body centre while hanging
export const HAND = 46; // hand above body centre while flying
export const CATCH_R = 36;
export const MAGNET_R = 70;
export const tuning = { magnet: true };
export const MAX_ANGLE = 2.4;
export const WALL_PAD = 16;
export const BOLT_EVERY_M = 50;
// Holds stay this far from the sides so the swinging climber never leaves the view.
const EDGE = ARM + 24;
export const RESPAWN_S = 1.1;

const G = 1700;
const W0SQ = G / ARM;
const PUMP = 16;
const DAMP = 0.35;
const BOOST = 1.3;
const FALL_LIMIT = 480;
const REGRAB_DELAY = 0.25;
const PUMP_DRAIN = 1.15;
const RAIN_DRAIN = 1.5;

export const GRIP_TIME: Record<HoldType, number> = {
  start: Infinity,
  bolt: Infinity,
  jug: 12,
  crimp: 7,
  sloper: 4.5,
  summit: Infinity,
};

export const MILESTONES: [number, string][] = [
  [100, "The Apron"],
  [350, "Bellygood Ledge"],
  [SUMMIT_M, "Summit"],
];

export type Game = {
  holds: Hold[];
  nextId: number;
  tip: Hold;
  backups: Hold[];
  nextBolt: number;
  checkpoint: Hold;
  falls: number;
  fallTimer: number;
  phase: Phase;
  hold: Hold;
  theta: number;
  omega: number;
  pos: Vec;
  vel: Vec;
  pressed: boolean;
  wasPressed: boolean;
  released: Hold | null;
  sinceRelease: number;
  cam: number;
  height: number;
  started: boolean;
  elapsed: number;
  rain: number;
  nextRain: number;
  message: string;
};

const rand = (min: number, max: number) => Math.random() * (max - min) + min;
const clamp = (v: number, min: number, max: number) =>
  Math.min(max, Math.max(min, v));

export function swing(
  theta: number,
  omega: number,
  pumping: boolean,
  dt: number,
): [number, number] {
  const push = pumping
    ? PUMP * (Math.abs(omega) > 0.05 ? Math.sign(omega) : 1)
    : 0;
  omega += (-W0SQ * Math.sin(theta) - DAMP * omega + push) * dt;
  theta += omega * dt;
  if (Math.abs(theta) > MAX_ANGLE) {
    theta = Math.sign(theta) * MAX_ANGLE;
    omega = 0;
  }
  return [theta, omega];
}

export const bodyAt = (h: Vec, theta: number): Vec => ({
  x: h.x + ARM * Math.sin(theta),
  y: h.y - ARM * Math.cos(theta),
});

const launchVel = (theta: number, omega: number, boost: number): Vec => ({
  x: ARM * omega * Math.cos(theta) * boost,
  y: ARM * omega * Math.sin(theta) * boost,
});

function fly(p: Vec, v: Vec, dt: number) {
  v.y -= G * dt;
  p.x += v.x * dt;
  p.y += v.y * dt;
  if (p.x < WALL_PAD) {
    p.x = WALL_PAD;
    v.x = Math.abs(v.x) * 0.4;
  } else if (p.x > W - WALL_PAD) {
    p.x = W - WALL_PAD;
    v.x = -Math.abs(v.x) * 0.4;
  }
}

export const crossed = (a: number, b: number, t: number) =>
  a !== b && (a - t) * (b - t) <= 0;

// Simulate a full-power swing from `from` and pick a catchable point on the
// resulting flight path. Uses the same step functions and timestep as play.
function flightPath(from: Hold, dir: 1 | -1, releaseAt: number): Vec[] {
  let th = -dir * MAX_ANGLE;
  let om = 0;
  let prev = th;
  let launched = false;
  for (let i = 0; i < 600; i++) {
    [th, om] = swing(th, om, true, DT);
    if (Math.sign(om) === dir && crossed(prev, th, releaseAt)) {
      launched = true;
      break;
    }
    prev = th;
  }
  if (!launched) return [];

  const p = bodyAt(from, th);
  const v = launchVel(th, om, BOOST);
  const pts: Vec[] = [];
  for (let i = 0; i < 180; i++) {
    fly(p, v, DT);
    if (p.x <= 40 || p.x >= W - 40 || v.y < -250) break;
    const hand = { x: p.x, y: p.y + HAND };
    if (hand.y > from.y + 60 && hand.x > EDGE && hand.x < W - EDGE)
      pts.push(hand);
  }
  return pts;
}

const pick = <T>(xs: T[]) => xs[Math.floor(Math.random() * xs.length)];

// Find a release that carries the hand through `target`, or null.
function aimAt(from: Hold, target: Vec): Plan | null {
  let best: Plan | null = null;
  let bestD = CATCH_R * 0.6;
  for (const dir of [1, -1] as const) {
    for (let k = 0; k <= 36; k++) {
      const releaseAt = dir * (-0.3 + (1.3 * k) / 36) * MAX_ANGLE;
      for (const p of flightPath(from, dir, releaseAt)) {
        const d = Math.hypot(p.x - target.x, p.y - target.y);
        if (d < bestD) {
          bestD = d;
          best = { dir, theta: releaseAt };
        }
      }
    }
  }
  return best;
}

function planJump(
  from: Hold,
): { plan: Plan; target: Vec; backups: Vec[] } | null {
  for (let tries = 0; tries < 40; tries++) {
    const dir: 1 | -1 = Math.random() < 0.5 ? 1 : -1;
    const releaseAt = dir * rand(-0.2, 0.9) * MAX_ANGLE;
    const pts = flightPath(from, dir, releaseAt);
    if (!pts.length) continue;
    // Backup holds on the paths of slightly early and late releases, so a
    // near-miss still has something to grab.
    const backups: Vec[] = [];
    for (const off of [-0.3, 0.3]) {
      const alt = flightPath(from, dir, releaseAt + off);
      if (alt.length && Math.random() < 0.7) backups.push(pick(alt));
    }
    return { plan: { dir, theta: releaseAt }, target: pick(pts), backups };
  }
  return null;
}

function randomType(): HoldType {
  const r = Math.random();
  return r < 0.35 ? "jug" : r < 0.8 ? "crimp" : "sloper";
}

function makeHold(g: Game, x: number, y: number, type: HoldType): Hold {
  const hold = { id: g.nextId++, x, y, type, grip: GRIP_TIME[type] };
  g.holds.push(hold);
  return hold;
}

// Grow the route upward. The main chain is planned jump by jump; each step
// may also get backup holds on the paths of slightly early/late releases.
// A backup is only kept if it has its own planned jump onward to the next
// chain hold, so the route never dead-ends.
function extendRoute(g: Game, upTo: number) {
  while (g.tip.type !== "summit" && g.tip.y < upTo) {
    const jump = planJump(g.tip);
    const target = jump
      ? jump.target
      : { x: clamp(g.tip.x + rand(-40, 40), 60, W - 60), y: g.tip.y + 60 };
    if (jump) g.tip.plan = jump.plan;
    const summit = target.y >= SUMMIT_Y;
    const bolt = !summit && target.y >= g.nextBolt;
    if (bolt) g.nextBolt += BOLT_EVERY_M * PX_PER_M;
    const next = makeHold(
      g,
      target.x,
      target.y,
      summit ? "summit" : bolt ? "bolt" : randomType(),
    );

    for (const b of g.backups) {
      const plan = aimAt(b, next);
      if (plan) b.plan = plan;
      else g.holds = g.holds.filter((h) => h !== b);
    }
    g.backups = [];

    if (jump && !summit) {
      for (const b of jump.backups) {
        const clear = g.holds.every(
          (h) => Math.hypot(h.x - b.x, h.y - b.y) > 70,
        );
        if (clear && b.y < SUMMIT_Y - 80)
          g.backups.push(makeHold(g, b.x, b.y, randomType()));
      }
    }
    g.tip = next;
  }
}

export function newGame(): Game {
  const start: Hold = {
    id: 1,
    x: W / 2,
    y: START_Y,
    type: "start",
    grip: Infinity,
  };
  const g: Game = {
    holds: [start],
    nextId: 2,
    tip: start,
    backups: [],
    nextBolt: START_Y + BOLT_EVERY_M * PX_PER_M,
    checkpoint: start,
    falls: 0,
    fallTimer: 0,
    phase: "hanging",
    hold: start,
    theta: 0,
    omega: 0,
    pos: bodyAt(start, 0),
    vel: { x: 0, y: 0 },
    pressed: false,
    wasPressed: false,
    released: null,
    sinceRelease: 0,
    cam: -30,
    height: 0,
    started: false,
    elapsed: 0,
    rain: 0,
    nextRain: rand(18, 28),
    message: "Hold Space (or press and hold) to swing. Let go to jump.",
  };
  extendRoute(g, START_Y + H + 300);
  return g;
}

export const isOver = (g: Game) => g.phase === "summit";

export const heightNow = (g: Game) =>
  clamp(
    ((g.phase === "flying" || g.phase === "falling" ? g.pos.y : g.hold.y) -
      START_Y) /
      PX_PER_M,
    0,
    SUMMIT_M,
  );

function launch(g: Game, boost: number) {
  g.vel = launchVel(g.theta, g.omega, boost);
  g.phase = "flying";
  g.released = g.hold;
  g.sinceRelease = 0;
  g.started = true;
}

function grab(g: Game, h: Hold) {
  const dx = g.pos.x - h.x;
  const dy = h.y - g.pos.y;
  g.theta = Math.atan2(dx, dy);
  const tangential = g.vel.x * Math.cos(g.theta) + g.vel.y * Math.sin(g.theta);
  g.omega = clamp((tangential / ARM) * 0.5, -6, 6);
  g.pos = bodyAt(h, g.theta);
  g.hold = h;
  g.released = null;
  g.height = Math.max(g.height, Math.min(SUMMIT_M, (h.y - START_Y) / PX_PER_M));
  if (h.type === "summit") {
    g.phase = "summit";
    g.message = "Summit! You sent the Chief. 🎉";
    return;
  }
  g.phase = "hanging";
  if (h.type === "bolt") {
    if (h.y > g.checkpoint.y) {
      g.checkpoint = h;
      g.message = `Clipped the bolt at ${Math.round((h.y - START_Y) / PX_PER_M)} m. Falls stop here now.`;
    } else g.message = "Resting on the bolt.";
    return;
  }
  g.message =
    h.grip <= 0.5
      ? "That hold's already greasy…"
      : h.type === "jug"
        ? "Jug! Catch your breath."
        : h.type === "sloper"
          ? "Sloper! Don't hang around."
          : "Crimp. Keep moving.";
}

// Gentle pull toward a nearby hold so near-misses feel fair.
function magnet(g: Game, dt: number) {
  if (!tuning.magnet) return;
  const hand = { x: g.pos.x, y: g.pos.y + HAND };
  let best: Hold | null = null;
  let bestD = MAGNET_R;
  for (const h of g.holds) {
    if (h === g.released && g.sinceRelease < REGRAB_DELAY) continue;
    if (h.grip <= 0) continue;
    const d = Math.hypot(hand.x - h.x, hand.y - h.y);
    if (d < bestD) {
      best = h;
      bestD = d;
    }
  }
  if (!best) return;
  const k = 9 * dt * (1 - bestD / MAGNET_R);
  g.pos.x += (best.x - hand.x) * k;
  g.pos.y += (best.y - hand.y) * k;
}

export function step(g: Game, dt: number) {
  if (isOver(g)) {
    g.wasPressed = g.pressed;
    return;
  }
  if (g.phase === "falling") {
    g.elapsed += dt;
    fly(g.pos, g.vel, dt);
    g.fallTimer -= dt;
    if (g.fallTimer <= 0) {
      g.phase = "hanging";
      g.hold = g.checkpoint;
      g.theta = 0;
      g.omega = 0;
      g.pos = bodyAt(g.hold, 0);
      g.released = null;
      for (const h of g.holds) h.grip = GRIP_TIME[h.type];
      g.message =
        g.checkpoint.type === "start"
          ? "Back at the start. Shake it off."
          : "Caught by the rope. Keep going!";
    }
    follow(g, dt);
    g.wasPressed = g.pressed;
    return;
  }

  if (g.started) {
    g.elapsed += dt;
    g.nextRain -= dt;
    if (g.nextRain <= 0) {
      g.rain = 8;
      g.nextRain = rand(22, 35);
      g.message = "Squamish drizzle! Every hold is greasy.";
    }
    g.rain = Math.max(0, g.rain - dt);
  }

  if (g.phase === "hanging") {
    if (g.wasPressed && !g.pressed) {
      launch(g, BOOST);
    } else {
      [g.theta, g.omega] = swing(g.theta, g.omega, g.pressed, dt);
      g.pos = bodyAt(g.hold, g.theta);
      if (Number.isFinite(g.hold.grip)) {
        const drain =
          (g.pressed ? PUMP_DRAIN : 1) * (g.rain > 0 ? RAIN_DRAIN : 1);
        g.hold.grip -= dt * drain;
        if (g.hold.grip <= 0) {
          g.hold.grip = 0;
          launch(g, 1);
          g.message = "Your grip gave out!";
        }
      }
    }
  }

  if (g.phase === "flying") {
    fly(g.pos, g.vel, dt);
    g.sinceRelease += dt;
    magnet(g, dt);
    const hand = { x: g.pos.x, y: g.pos.y + HAND };
    for (const h of g.holds) {
      if (h === g.released && g.sinceRelease < REGRAB_DELAY) continue;
      if (h.grip <= 0) continue;
      if (Math.hypot(hand.x - h.x, hand.y - h.y) < CATCH_R) {
        grab(g, h);
        break;
      }
    }
    if (
      g.phase === "flying" &&
      (g.pos.y < 0 || g.pos.y < g.hold.y - FALL_LIMIT)
    ) {
      g.phase = "falling";
      g.falls += 1;
      g.fallTimer = RESPAWN_S;
      g.message = "Whipper!";
    }
  }

  follow(g, dt);
  g.wasPressed = g.pressed;
}

function follow(g: Game, dt: number) {
  const focus = g.phase === "hanging" ? g.hold.y : g.pos.y;
  extendRoute(g, focus + H + 300);
  const target = Math.max(-30, focus - 300);
  g.cam += (target - g.cam) * Math.min(1, dt * 5);
  g.holds = g.holds.filter(
    (h) =>
      h.y > Math.min(g.cam - 200, g.checkpoint.y - 1) ||
      h === g.hold ||
      h === g.checkpoint ||
      h === g.tip ||
      g.backups.includes(h),
  );
}
